icorp/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import forms
from . import views


app_name = 'account'

#
urlpatterns = [
    # Вход
    path('login/',
         auth_views.LoginView.as_view(
             form_class=forms.UserLoginForm,
             template_name='registration/login.html',
         ),
         name='login'),
    # Выход
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #
    # # Сменить пароль
    # path('password_change/',
    #      auth_views.PasswordChangeView.as_view(),
    #      name='password_change'),
    # # Успешно изменил пароль
    # path('password_change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),
    #
    # # Сбрось пароля
    # path('password_reset/',
    #      auth_views.PasswordResetView.as_view(),
    #      name='password_reset'),
    # # Ссылка отправлена
    # path('password_reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # # Ссылка подверждения для сброса пароля UID
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # # Успешно сбросил пароль
    # path('reset/complete/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),

    path('', views.dashboard, name='dashboard'),
]

icorp/icorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("worker.urls")),
    path('tasker/', include("tasker.urls", namespace="tasker")),
    path('account/', include("account.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

icorp/tasker/urls.py
from django.urls import path, include

from . import views

app_name = 'tasker'

urlpatterns = [
    path('', include('tasker.api_urls')),
    path('create_profile/', views.create_profile_list, name='create_profile_list'),
    path('create_profile/<int:pk>/', views.create_profile_detail, name='create_profile_detail'),
    path('create_password/<int:pk>/', views.add_password, name='create_password'),

]

icorp/templates/navbar/account_dropdown.html
{% load static %}
<div class="dropdown ms-2">
    <a id="userSettings" class="dropdown-toggle d-flex py-2 align-items-center text-decoration-none" href="#!"
       role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{% static 'assets/images/user.png' %}" class="rounded-2 img-3x"/>
        <span class="ms-2 text-truncate d-lg-block d-none">Anne Santiago</span>
    </a>
    <!-- TODO dropdown menu -->
    <div class="dropdown-menu dropdown-menu-end shadow-lg">
        <div class="header-action-links mx-3 gap-2">
            <a class="dropdown-item" href="profile.html"><i class="bi bi-person text-primary"></i>Profile</a>
            <a class="dropdown-item" href="settings.html"><i class="bi bi-gear text-danger"></i>Settings</a>
            <a class="dropdown-item" href="widgets.html"><i class="bi bi-box text-success"></i>Widgets</a>
        </div>
        <div class="mx-3 mt-2 d-grid">
            <a href="login.html" class="btn btn-primary btn-sm">Logout</a>
        </div>
    </div>
</div>

icorp/templates/navbar/brand.html
{% load static %}
<div class="app-brand py-2 ms-3">
    <a href="index.html" class="d-sm-block d-none">
        <img src="{% static 'assets/images/logo.svg' %}" class="logo"/>
    </a>
    <a href="index.html" class="d-sm-none d-block">
        <img src="{% static 'assets/images/logo-sm.svg' %}" class="logo"/>
    </a>
</div

icorp/templates/navbar/sidebar_menu.html
{% load static %}
{% load worker_tags %}
<nav id="sidebar" class="sidebar-wrapper">
    <!-- Sidebar menu starts -->
    <div class="sidebarMenuScroll">
        <ul class="sidebar-menu">
            <li {% if section == 'dashboard' %} class="active current-page" {% endif %}>
                <a href="{% url 'account:dashboard' %}">
                    <i class="bi bi-pie-chart"></i>
                    <span class="menu-text">Dashboard</span>
                </a>
            </li>
            <!-- Форма для запольнения заявки на создания сотрдника должен быть виден только HR-creater -->

            <li {% if section == 'profiles' %} class="active current-page" {% endif %}>
                <a href="{% url 'profiles' %}">
                    <i class="bi bi-person-plus"></i>
                    <span class="menu-text">Сотрудники</span>
                </a>
            </li>
            {% is_admin_creater_profile request.user as is_admin %}
            {% if is_admin %}
            <li {% if section == 'crate_profile' %} class="active current-page" {% endif %}>
                <a href="{% url 'tasker:create_profile_list' %}">
                    <i class="fs-3 bi bi-person-rolodex"></i>
                    <span class="menu-text">Создать профили</span>
                </a>
            </li>
            {% endif %}
<!--            <li>-->
<!--                <a href="widgets.html">-->
<!--                    <i class="bi bi-box"></i>-->
<!--                    <span class="menu-text">Widgets</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="calendar.html">-->
<!--                    <i class="bi bi-calendar2"></i>-->
<!--                    <span class="menu-text">Calendar</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-stickies"></i>-->
<!--                    <span class="menu-text">Components</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="accordions.html">Accordions</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="alerts.html">Alerts</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="buttons.html">Buttons</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="badges.html">Badges</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="carousel.html">Carousel</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="list-items.html">List Items</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="progress.html">Progress Bars</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="popovers.html">Popovers</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="tooltips.html">Tooltips</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-ui-checks-grid"></i>-->
<!--                    <span class="menu-text">Forms</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="form-inputs.html">Form Inputs</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="form-checkbox-radio.html">Checkbox &amp; Radio</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="form-file-input.html">File Input</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="form-validations.html">Validations</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="date-time-pickers.html">Date Time Pickers</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="form-layouts.html">Form Layouts</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-window-sidebar"></i>-->
<!--                    <span class="menu-text">Invoices</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="create-invoice.html">Create Invoice</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="view-invoice.html">View Invoice</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="invoice-list.html">Invoice List</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="tables.html">-->
<!--                    <i class="bi bi-border-all"></i>-->
<!--                    <span class="menu-text">Tables</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="events.html">-->
<!--                    <i class="bi bi-calendar4"></i>-->
<!--                    <span class="menu-text">Events</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="subscribers.html">-->
<!--                    <i class="bi bi-check-circle"></i>-->
<!--                    <span class="menu-text">Subscribers</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="contacts.html">-->
<!--                    <i class="bi bi-wallet2"></i>-->
<!--                    <span class="menu-text">Contacts</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="settings.html">-->
<!--                    <i class="bi bi-gear"></i>-->
<!--                    <span class="menu-text">Settings</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="profile.html">-->
<!--                    <i class="bi bi-person-square"></i>-->
<!--                    <span class="menu-text">Profile</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-code-square"></i>-->
<!--                    <span class="menu-text">Cards</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="cards.html">Cards</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="advanced-cards.html">Advanced Cards</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-pie-chart"></i>-->
<!--                    <span class="menu-text">Graphs</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="apex.html">Apex</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="morris.html">Morris</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="maps.html">-->
<!--                    <i class="bi bi-pin-map"></i>-->
<!--                    <span class="menu-text">Maps</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="tabs.html">-->
<!--                    <i class="bi bi-slash-square"></i>-->
<!--                    <span class="menu-text">Tabs</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="modals.html">-->
<!--                    <i class="bi bi-terminal"></i>-->
<!--                    <span class="menu-text">Modals</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="icons.html">-->
<!--                    <i class="bi bi-textarea"></i>-->
<!--                    <span class="menu-text">Icons</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="typography.html">-->
<!--                    <i class="bi bi-explicit"></i>-->
<!--                    <span class="menu-text">Typography</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-upc-scan"></i>-->
<!--                    <span class="menu-text">Login/Signup</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="login.html">Login</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="signup.html">Signup</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="forgot-password.html">Forgot Password</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="page-not-found.html">-->
<!--                    <i class="bi bi-exclamation-diamond"></i>-->
<!--                    <span class="menu-text">Page Not Found</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="maintenance.html">-->
<!--                    <i class="bi bi-exclamation-octagon"></i>-->
<!--                    <span class="menu-text">Maintenance</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="treeview">-->
<!--                <a href="#!">-->
<!--                    <i class="bi bi-code-square"></i>-->
<!--                    <span class="menu-text">Multi Level</span>-->
<!--                </a>-->
<!--                <ul class="treeview-menu">-->
<!--                    <li>-->
<!--                        <a href="#!">Level One Link</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="#!">-->
<!--                            Level One Menu-->
<!--                            <i class="bi bi-chevron-right"></i>-->
<!--                        </a>-->
<!--                        <ul class="treeview-menu">-->
<!--                            <li>-->
<!--                                <a href="#!">Level Two Link</a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#!">Level Two Menu-->
<!--                                    <i class="bi bi-chevron-right"></i>-->
<!--                                </a>-->
<!--                                <ul class="treeview-menu">-->
<!--                                    <li>-->
<!--                                        <a href="#!">Level Three Link</a>-->
<!--                                    </li>-->
<!--                                    <li>-->
<!--                                        <a href="#!">Level Three Link</a>-->
<!--                                    </li>-->
<!--                                </ul>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="#!">Level One Link</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->
    <!-- Sidebar menu ends -->

</nav>

icorp/templates/navbar/toggle_button.html
{% load static %}
<div class="d-flex">
    <button class="toggle-sidebar" id="toggle-sidebar">
        <i class="bi bi-list lh-1"></i>
    </button>
    <button class="pin-sidebar" id="pin-sidebar">
        <i class="bi bi-list lh-1"></i>
    </button>
</div>